const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{chromium}=require('playwright');
const root=path.resolve('www');
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://local'),file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(error,data)=>{if(error){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:393,height:873},locale:'hu-HU',timezoneId:'Europe/Budapest'}),errors=[];p.on('pageerror',e=>errors.push(String(e)));p.on('dialog',d=>d.accept());fs.mkdirSync('ui-evidence',{recursive:true});
 await p.goto('http://127.0.0.1:'+server.address().port);await p.waitForFunction(()=>TrainPilotBoot.finished);
 await p.evaluate(()=>{db.set('settings',{...settings(),rest:90,profile:{age:30,goal:'fitness',experience:'beginner',minutes:45}});db.set('history',[1,2].map(i=>({id:'goal-'+i,started:new Date(Date.now()-i*120000).toISOString(),finished:new Date(Date.now()-i*60000).toISOString(),exercises:[{...byId('running'),sets:[{done:true,reps:'600',distanceMeters:2000}]}]})));});
 for(const width of [320,360,393,412])for(const lang of ['hu','en','de','ro'])for(const theme of ['classicBlue','blue']){
  const label=width+'/'+lang+'/'+theme;await p.setViewportSize({width,height:width===320?740:873});await p.evaluate(({lang,theme})=>{tp155R4ClosePanel(false);db.set('language',lang);db.set('settings',{...settings(),activityGoals110:{weekWorkouts:0,monthKm:0}});rf200SetTheme(theme);go('home');},{lang,theme});
  const before=await p.locator('#app main.rf221-home').boundingBox();assert.equal(await p.locator('#app .tp110-goal-mini').count(),1,label+' first-render goal entry: '+await p.locator('#rf223Today').innerHTML());await p.locator('#app .tp110-goal-mini').click();assert.equal(await p.locator('#tp155R4PanelHost').getAttribute('data-panel'),'goals',label+' goal button must open Goals, not Coach');
  await p.locator('input[name="weekWorkouts"]').fill('3');await p.locator('input[name="monthKm"]').fill('10');await p.locator('.tp110-goals button[type="submit"]').click();
  const goalValues=await p.evaluate(()=>({settings:settings().activityGoals110,backup:makeBackup().settings.activityGoals110,rest:settings().rest}));assert.deepEqual(goalValues.settings,{weekWorkouts:3,monthKm:10});assert.deepEqual(goalValues.backup,goalValues.settings);assert.equal(goalValues.rest,90);
  assert.equal(await p.locator('.tp110-goal progress').count(),2);assert.equal(await p.locator('.tp110-goal progress').first().getAttribute('value'),'2');assert.equal(await p.locator('.tp110-goal progress').nth(1).getAttribute('value'),'4');
  await p.locator('input[name="weekWorkouts"]').fill('22');await p.locator('.tp110-goals button[type="submit"]').click();assert.equal(await p.evaluate(()=>settings().activityGoals110.weekWorkouts),3,'invalid target must not partially save');
  await p.evaluate(()=>tp155R4ClosePanel(false));const after=await p.locator('#app main.rf221-home').boundingBox();assert.equal(after.height,before.height,label+' goals do not grow the fixed Home card');assert.ok(await p.evaluate(()=>document.documentElement.scrollHeight-innerHeight)<=1,label+' normal Home stays fixed');
  await p.locator('#app .tp110-goal-mini').click();await p.locator('input[name="weekWorkouts"]').fill('0');await p.locator('.tp110-goals button[type="submit"]').click();await p.evaluate(()=>tp155R4ClosePanel(false));assert.match(await p.locator('#app .tp110-goal-mini').innerText(),/4\/10.*km/);
  if(width===393&&lang==='hu'&&theme==='blue')await p.screenshot({path:'ui-evidence/goals-home-2698.png'});
 }
 await p.setViewportSize({width:393,height:873});await p.evaluate(()=>{tp155R4ClosePanel(false);db.set('language','hu');go('home');});await p.locator('.tp110-goal-mini').click();
 await p.evaluate(()=>{window.__write110=db.set;db.set=function(key,value){if(key==='settings')throw Error('quota');return window.__write110(key,value);};});await p.locator('input[name="monthKm"]').fill('20');await p.locator('.tp110-goals button[type="submit"]').click();assert.equal(await p.evaluate(()=>settings().activityGoals110.monthKm),10);assert.equal(await p.locator('[data-tp110-status]').getAttribute('data-kind'),'error');await p.evaluate(()=>{db.set=window.__write110;tp155R4ClosePanel(false);});
 await p.reload();await p.waitForFunction(()=>TrainPilotBoot.finished);assert.deepEqual(await p.evaluate(()=>settings().activityGoals110),{weekWorkouts:0,monthKm:10},'goals persist after restart');

 const fixture=await p.evaluate(()=>{const today=new Date();today.setHours(8,0,0,0);const at=offset=>{const d=new Date(today);d.setDate(d.getDate()+offset);return d;};const item=(id,offset,day,status='planned',programId='home-basic')=>({id,programId,dayId:day,workout:day,start:at(offset).toISOString(),end:new Date(+at(offset)+2700000).toISOString(),status,cancelled:false,updatedAt:1});const rows=[item('miss-110',-2,'A'),item('next-110',1,'B'),item('later-110',3,'A'),item('done-110',-4,'B','completed')];db.set('scheduled',rows);db.set('activeProgramId','home-basic');db.set('plannerSettings',{...plannerSettings(),mode:'alternate'});go('calendar');return rows;});
 await p.locator('.tp110-replan-link').click();assert.equal(await p.locator('#tp155R4PanelHost').getAttribute('data-panel'),'replan');assert.equal(await p.locator('.tp110-replan-row').count(),3);
 await p.evaluate(()=>{const start=new Date(document.getElementById('tp110ReplanDate').value+'T10:00');db.set('scheduled',[...scheduled(),{id:'other-110',programId:'gym',dayId:'A',workout:'A',start:start.toISOString(),end:new Date(+start+3600000).toISOString(),status:'planned',cancelled:false}]);});
 await p.locator('[data-tp110-apply]').click();assert.deepEqual((await p.evaluate(()=>scheduled())).slice(0,4),fixture,'stale preview must not apply without review');assert.equal(await p.locator('[data-tp110-replan-status]').getAttribute('data-kind'),'pending');
 await p.locator('[data-tp110-apply]').click();const replanned=await p.evaluate(()=>scheduled());assert.deepEqual(replanned.slice(0,3).map(x=>x.id),['miss-110','next-110','later-110']);assert.deepEqual(replanned.slice(0,3).map(x=>x.dayId),['A','B','A']);assert.deepEqual(replanned[3],fixture[3]);assert.ok(replanned.every((x,i)=>i===3||Date.parse(x.start)>Date.now()));assert.equal(await p.locator('[data-tp110-replan-status]').getAttribute('data-kind'),'success');
 await p.screenshot({path:'ui-evidence/replan-saved-2698.png'});await p.evaluate(()=>tp155R4ClosePanel(false));

 await p.evaluate(()=>{state.session=null;db.set('draft',null);go('plan');});await p.locator('.tp150-quick-entry button').click();const running=p.locator('[data-exercise-id="running"]');await running.locator('.tp150-quick-copy').click();await running.locator('.tp150-quick-start').click();await p.waitForSelector('#tp107Indoor');
 await p.evaluate(()=>{window.__cues110=0;navigator.vibrate=()=>{window.__cues110++;return true;};});await p.locator('.tp110-interval>summary').click();
 const form=p.locator('.tp110-interval form');await form.locator('[name="work"]').fill('1');await form.locator('[name="rest"]').fill('1');await form.locator('[name="rounds"]').fill('2');await form.locator('[name="sound"]').uncheck();await form.locator('button[type="submit"]').click();assert.equal(await form.locator('[data-tp110-interval-status]').getAttribute('data-kind'),'success');
 await form.locator('button[type="button"]').click();assert.equal(await form.locator('[name="work"]').isDisabled(),true);await p.waitForFunction(()=>document.querySelector('[data-tp110-phase]').textContent.includes('Pihenő'));await p.waitForFunction(()=>document.querySelector('[data-tp110-phase]').textContent.includes('2/2'));await p.waitForFunction(()=>document.querySelector('[data-tp110-phase]').textContent.includes('teljesítve'));
 assert.deepEqual(await p.evaluate(()=>({seconds:state.session.exercises[0].sets[0].reps,running:state.session.indoorTimer107.running,done:state.session.exercises[0].sets[0].done,cues:window.__cues110})),{seconds:'3',running:false,done:false,cues:4});assert.equal(await p.locator('[data-tp107-clock-toggle]').isDisabled(),true);await p.screenshot({path:'ui-evidence/interval-complete-2698.png'});
 await p.locator('button[onclick="tp107ResetIndoor()"]').click();await p.locator('#tp2628Dialog [data-tp2628-confirm]').click();assert.equal(await p.evaluate(()=>state.session.exercises[0].sets[0].reps),'0');
 await form.locator('[name="work"]').fill('2');await form.locator('button[type="button"]').click();await p.evaluate(()=>{state.session.indoorTimer107.startedAt=Date.now()-2100;tp107PaintIndoor();});await p.locator('[data-tp107-clock-toggle]').click();const paused=await p.evaluate(()=>({setId:state.session.indoorTimer107.setId,elapsed:state.session.indoorTimer107.elapsedMs}));await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>state.session.indoorTimer107.elapsedMs),paused.elapsed);
 await p.reload();await p.waitForFunction(()=>TrainPilotBoot.finished);await p.evaluate(()=>resumeDraft());assert.equal(await p.evaluate(()=>state.session.indoorTimer107.setId),paused.setId);assert.equal(await p.evaluate(()=>state.session.indoorTimer107.running),false);await p.locator('[data-tp107-clock-toggle]').click();
 await p.reload();await p.waitForFunction(()=>TrainPilotBoot.finished);await p.evaluate(()=>{resumeDraft();state.session.indoorTimer107.startedAt=Date.now()-999000;tp107PaintIndoor();});assert.equal(await p.evaluate(()=>state.session.exercises[0].sets[0].reps),'5','background/restart recovery must stop at the planned end');await p.evaluate(()=>toggleSet(0,0));assert.equal(await p.evaluate(()=>state.session.indoorTimer107),undefined,'completing the owner set clears interval runtime');
 await p.evaluate(()=>{state.session=null;db.set('draft',null);go('home');state.health.recovery={sleepMinutes:300,sleepEnd:new Date().toISOString(),hrvRmssdMs:30,hrvBaselineMs:50,hrvTime:new Date().toISOString(),day:localDateKey(new Date())};db.set('history',[{id:'pain-110',started:new Date(Date.now()-3600000).toISOString(),finished:new Date(Date.now()-1800000).toISOString(),exercises:[{...byId('db-floor-press'),effort:'pain',sets:[{done:true,reps:'10',weight:10}]}]}]);go('coach');});
 const reason=await p.locator('.tp151-coach-context').innerText();assert.match(reason,/5 h/);assert.match(reason,/30 ms \/ 50 ms/);assert.match(reason,/-14/);assert.match(reason,/-12/);assert.match(reason,/Fájdalom/);await p.screenshot({path:'ui-evidence/coach-reasons-2698.png'});
 await p.evaluate(()=>{tp155R4ClosePanel(false);db.set('history',[]);go('history');});assert.equal(await p.locator('#app .tp110-empty').count(),1);await p.locator('#app .tp110-empty button').click();assert.equal(await p.evaluate(()=>state.tab),'plan');await p.evaluate(()=>tp107OpenCardio());assert.equal(await p.locator('.tp107-cardio .tp110-empty').count(),1);

 await p.addStyleTag({content:'html.tp110-large-text body #app main :is(p,small,label,.btn,.tp5-today-label,.tp5-today-value){font-size:20px!important;line-height:1.4!important}html.tp110-large-text body #tp155R4PanelHost :is(p,label,.btn,.field){font-size:20px!important;line-height:1.4!important}html.tp110-large-text body .top :is(.tp151-nav-label,.tp154-nav-action-label){font-size:18px!important}'});
 await p.evaluate(async()=>{const old=window.Capacitor;window.Capacitor={isNativePlatform:()=>true,Plugins:{AppFeedback:{appearance:async()=>({fontScale:1.6})}}};await TrainPilot110.updateAppearance();window.Capacitor=old;});assert.equal(await p.evaluate(()=>document.documentElement.classList.contains('tp110-large-text')),true);
 for(const width of [320,360,393,412])for(const lang of ['hu','en','de','ro']){
  await p.setViewportSize({width,height:740});await p.evaluate(lang=>{tp155R4ClosePanel(false);db.set('language',lang);go('home');},lang);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth)<=1,'large text Home has no horizontal overflow '+width+'/'+lang);
  await p.locator('#app .tp110-goal-mini').click();await p.locator('.tp110-goals button[type="submit"]').scrollIntoViewIfNeeded();assert.equal(await p.locator('.tp110-goals button[type="submit"]').isVisible(),true);await p.evaluate(()=>tp155R4ClosePanel(false));
  await p.evaluate(()=>go('health'));await p.locator('.tp168-health-note').scrollIntoViewIfNeeded();assert.ok(await p.evaluate(()=>document.querySelector('.tp168-health-note').getBoundingClientRect().bottom<=innerHeight+1),'large text Health footer reachable '+width+'/'+lang);
  await p.evaluate(()=>go('calendar'));await p.locator('.rf2211-planner .btn.tp155-auto-plan-only').scrollIntoViewIfNeeded();assert.ok(await p.evaluate(()=>document.querySelector('.rf2211-planner .btn.tp155-auto-plan-only').getBoundingClientRect().bottom<=innerHeight+1),'large text calendar planning remains reachable '+width+'/'+lang);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth)<=1);
  await p.evaluate(()=>tp155R4ClosePanel(false));
 }
 assert.deepEqual(errors,[]);console.log('PASS #103 UI: goals/backup/validation/quota/restart across 32 phone-language-theme cases; reviewed replanning; real interval cues, pause and draft recovery; concrete Coach reasons, empty actions and enlarged-text reachability');
}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
