package com.repforge.app;

import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import androidx.activity.result.ActivityResult;
import com.getcapacitor.*;
import com.getcapacitor.annotation.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import java.util.zip.*;
import org.json.*;

/** Streams photo files; no image/base64 payload crosses the WebView bridge. */
@CapacitorPlugin(name="BackupArchive")
public class BackupArchivePlugin extends Plugin {
 private static final int JSON_LIMIT=20*1024*1024, PHOTO_LIMIT=6*1024*1024, MAX_ENTRIES=5002;
 private static final long ARCHIVE_LIMIT=500L*1024*1024;
 private volatile boolean busy; private File exporting;
 private File transactions() throws IOException {File d=new File(getContext().getNoBackupFilesDir(),"archive_transactions");mkdir(d);return d;}
 private void mkdir(File f)throws IOException{if(!f.isDirectory()&&!f.mkdirs())throw new IOException("Cannot create backup directory.");}
 private File photos()throws IOException{File d=new File(getContext().getFilesDir(),"workout_photos");mkdir(d);return d;}
 private File transaction(String id)throws IOException{if(!id.matches("[a-f0-9-]{36}"))throw new IOException("Invalid archive token.");return new File(transactions(),id);}
 private void remove(File f)throws IOException{if(f.isDirectory()){File[] files=f.listFiles();if(files==null)throw new IOException("Cannot read backup directory.");for(File x:files)remove(x);}if(f.exists()&&!f.delete())throw new IOException("Cannot remove backup file.");}
 private long copy(InputStream in,OutputStream out,long limit)throws IOException{long total=0;byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){total+=n;if(total>limit)throw new IOException("Backup exceeds size limit.");out.write(b,0,n);}return total;}
 private byte[] read(File f,int max)throws IOException{try(InputStream in=new FileInputStream(f);ByteArrayOutputStream out=new ByteArrayOutputStream()){copy(in,out,max);return out.toByteArray();}}
 private void write(File f,byte[] data)throws IOException{try(FileOutputStream out=new FileOutputStream(f)){out.write(data);out.getFD().sync();}}
 private String hash(InputStream in)throws Exception{MessageDigest d=MessageDigest.getInstance("SHA-256");byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)d.update(b,0,n);StringBuilder s=new StringBuilder();for(byte x:d.digest())s.append(String.format(Locale.US,"%02x",x&255));return s.toString();}
 private String hash(File f)throws Exception{try(InputStream in=new FileInputStream(f)){return hash(in);}}
 private Set<String> photoIds(JSONObject data)throws Exception{Set<String> ids=new TreeSet<>();JSONArray history=data.optJSONArray("history");if(history==null)throw new IOException("Missing workout history.");for(int i=0;i<history.length();i++){JSONArray a=history.getJSONObject(i).optJSONArray("photos");if(a==null)continue;for(int j=0;j<a.length();j++){JSONObject p=a.getJSONObject(j);if(p.has("deletedAt")&&!p.isNull("deletedAt")&&p.optLong("deletedAt",-1)!=0&&!Boolean.FALSE.equals(p.opt("deletedAt"))&&!"".equals(p.opt("deletedAt")))continue;String id=p.optString("id");if(!id.matches("[a-f0-9-]{36}"))throw new IOException("Invalid photo reference.");ids.add(id);}}if(ids.size()>5000)throw new IOException("Too many photos.");return ids;}
 @PluginMethod public void save(PluginCall call){
  if(busy){call.reject("A file picker is already open.");return;}String raw=call.getString("data","");byte[] bytes=raw.getBytes(StandardCharsets.UTF_8);if(bytes.length==0||bytes.length>JSON_LIMIT){call.reject("Invalid backup size.");return;}busy=true;
  getBridge().execute(()->{try{
   JSONObject data=new JSONObject(raw),manifest=new JSONObject();manifest.put("format","TrainPilotArchive");manifest.put("version",1);JSONObject checks=new JSONObject();File tmp=File.createTempFile("trainpilot-",".zip",getContext().getCacheDir());long total=bytes.length;
   try(ZipOutputStream zip=new ZipOutputStream(new BufferedOutputStream(new FileOutputStream(tmp)))){
    zip.putNextEntry(new ZipEntry("backup.json"));zip.write(bytes);zip.closeEntry();checks.put("backup.json",hash(new ByteArrayInputStream(bytes)));
    for(String id:photoIds(data)){File photo=new File(photos(),id+".jpg");if(!photo.isFile()||photo.length()==0||photo.length()>PHOTO_LIMIT)throw new IOException("A referenced photo is missing. Download it from Drive before making a full backup.");total+=photo.length();if(total>ARCHIVE_LIMIT)throw new IOException("Maximum 500 MB per archive.");String name="photos/"+id+".jpg";zip.putNextEntry(new ZipEntry(name));MessageDigest digest=MessageDigest.getInstance("SHA-256");try(InputStream in=new java.security.DigestInputStream(new FileInputStream(photo),digest)){copy(in,zip,PHOTO_LIMIT);}zip.closeEntry();StringBuilder checksum=new StringBuilder();for(byte b:digest.digest())checksum.append(String.format(Locale.US,"%02x",b&255));checks.put(name,checksum.toString());}
    manifest.put("sha256",checks);byte[] manifestBytes=manifest.toString().getBytes(StandardCharsets.UTF_8);if(total+manifestBytes.length>ARCHIVE_LIMIT)throw new IOException("Maximum 500 MB expanded archive.");zip.putNextEntry(new ZipEntry("manifest.json"));zip.write(manifestBytes);zip.closeEntry();
   }exporting=tmp;call.getData().remove("data");
   Intent intent=new Intent(Intent.ACTION_CREATE_DOCUMENT);intent.addCategory(Intent.CATEGORY_OPENABLE);intent.setType("application/zip");intent.putExtra(Intent.EXTRA_TITLE,call.getString("name","TrainPilot.zip").replaceAll("[^a-zA-Z0-9._-]","_"));getBridge().executeOnMainThread(()->startActivityForResult(call,intent,"saved"));
  }catch(Exception e){busy=false;if(exporting!=null)exporting.delete();call.reject(e.getMessage(),e);}});
 }
 @ActivityCallback private void saved(PluginCall call,ActivityResult result){busy=false;File source=exporting;exporting=null;if(result.getResultCode()!=Activity.RESULT_OK||result.getData()==null){if(source!=null)source.delete();if(call!=null){JSObject r=new JSObject();r.put("cancelled",true);call.resolve(r);}return;}getBridge().execute(()->{try{if(source==null)throw new IOException("Export interrupted; retry the backup.");Uri uri=result.getData().getData();if(uri==null)throw new IOException("No file selected.");try(InputStream in=new FileInputStream(source);OutputStream out=getContext().getContentResolver().openOutputStream(uri,"w")){if(out==null)throw new IOException("Cannot write selected file.");copy(in,out,ARCHIVE_LIMIT+JSON_LIMIT);out.flush();}String actual;try(InputStream in=getContext().getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("Cannot verify exported file.");actual=hash(in);}if(!hash(source).equals(actual))throw new IOException("Export verification failed.");JSObject r=new JSObject();r.put("verified",true);r.put("bytes",source.length());r.put("name",call.getString("name","TrainPilot.zip"));call.resolve(r);}catch(Exception e){if(call!=null)call.reject(e.getMessage(),e);}finally{if(source!=null)source.delete();}});}
 @PluginMethod public void open(PluginCall c){if(busy){c.reject("A file picker is already open.");return;}busy=true;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/zip","application/x-zip-compressed"});startActivityForResult(c,i,"opened");}
 @ActivityCallback private void opened(PluginCall call,ActivityResult result){busy=false;if(result.getResultCode()!=Activity.RESULT_OK||result.getData()==null){JSObject r=new JSObject();r.put("cancelled",true);if(call!=null)call.resolve(r);return;}getBridge().execute(()->{File dir=null;try{
  Uri uri=result.getData().getData();if(uri==null)throw new IOException("No archive selected.");String token=UUID.randomUUID().toString();dir=transaction(token);mkdir(dir);File incoming=new File(dir,"incoming");mkdir(incoming);Set<String> names;
  try(InputStream raw=getContext().getContentResolver().openInputStream(uri)){if(raw==null)throw new IOException("Cannot read selected archive.");names=ArchiveIO.extract(raw,incoming,JSON_LIMIT,PHOTO_LIMIT,ARCHIVE_LIMIT,MAX_ENTRIES);}
  JSONObject data=new JSONObject(new String(read(new File(incoming,"backup.json"),JSON_LIMIT),StandardCharsets.UTF_8)),manifest=new JSONObject(new String(read(new File(incoming,"manifest.json"),JSON_LIMIT),StandardCharsets.UTF_8));if(!"TrainPilotArchive".equals(manifest.optString("format"))||manifest.optInt("version")!=1)throw new IOException("Unknown archive format.");JSONObject checks=manifest.getJSONObject("sha256");Set<String> expected=new HashSet<>();expected.add("backup.json");expected.add("manifest.json");for(String id:photoIds(data))expected.add("photos/"+id+".jpg");Map<String,String> hashes=new HashMap<>();Iterator<String> keys=checks.keys();while(keys.hasNext()){String k=keys.next();hashes.put(k,checks.getString(k));}ArchiveIO.verify(incoming,names,expected,hashes);
  JSObject r=new JSObject();r.put("data",data.toString());r.put("token",token);call.resolve(r);
 }catch(Exception e){if(dir!=null)try{remove(dir);}catch(Exception ignored){}if(call!=null)call.reject(e.getMessage(),e);}});}
 private void rollbackDir(File dir)throws Exception{File journal=new File(dir,"journal.json");if(!journal.isFile())return;JSONArray ids=new JSONArray(new String(read(journal,JSON_LIMIT),StandardCharsets.UTF_8));File originals=new File(dir,"originals");for(int i=0;i<ids.length();i++){String id=ids.getString(i);if(!id.matches("[a-f0-9-]{36}"))throw new IOException("Invalid restore journal.");File target=new File(photos(),id+".jpg"),old=new File(originals,id+".jpg");if(old.exists()){File temp=new File(photos(),id+".rollback");try(InputStream in=new FileInputStream(old);FileOutputStream out=new FileOutputStream(temp)){copy(in,out,PHOTO_LIMIT);out.getFD().sync();}if(target.exists()&&!target.delete())throw new IOException("Cannot replace rolled-back photo.");if(!temp.renameTo(target))throw new IOException("Cannot restore original photo.");}else if(target.exists()&&!target.delete())throw new IOException("Cannot roll back new photo.");}journal.delete();}
 @PluginMethod public void install(PluginCall c){getBridge().execute(()->{File dir=null;try{dir=transaction(c.getString("token",""));JSONObject data=new JSONObject(new String(read(new File(dir,"incoming/backup.json"),JSON_LIMIT),StandardCharsets.UTF_8));File original=new File(dir,"originals");mkdir(original);JSONArray touched=new JSONArray();for(String id:photoIds(data)){File dest=new File(photos(),id+".jpg"),src=new File(dir,"incoming/photos/"+id+".jpg");if(!src.isFile())throw new IOException("Photo archive missing.");if(dest.exists()){try(InputStream in=new FileInputStream(dest);FileOutputStream out=new FileOutputStream(new File(original,id+".jpg"))){copy(in,out,PHOTO_LIMIT);out.getFD().sync();}}touched.put(id);write(new File(dir,"journal.json"),touched.toString().getBytes(StandardCharsets.UTF_8));File tmp=new File(photos(),id+".restore");try(InputStream in=new FileInputStream(src);FileOutputStream out=new FileOutputStream(tmp)){copy(in,out,PHOTO_LIMIT);out.getFD().sync();}if(dest.exists()&&!dest.delete())throw new IOException("Cannot replace photo.");if(!tmp.renameTo(dest))throw new IOException("Cannot install photo.");}c.resolve();}catch(Exception e){if(dir!=null)try{rollbackDir(dir);}catch(Exception failure){c.reject("Photo rollback failed: "+failure.getMessage(),failure);return;}c.reject(e.getMessage(),e);}});}
 @PluginMethod public void rollback(PluginCall c){getBridge().execute(()->{try{rollbackDir(transaction(c.getString("token","")));c.resolve();}catch(Exception e){c.reject(e.getMessage(),e);}});}
 // Commit keeps rollback files until JavaScript has removed its durable restore marker.
 @PluginMethod public void commit(PluginCall c){c.resolve();}
 @PluginMethod public void discard(PluginCall c){getBridge().execute(()->{try{remove(transaction(c.getString("token","")));c.resolve();}catch(Exception e){c.reject(e.getMessage(),e);}});}
 @PluginMethod public void recover(PluginCall c){getBridge().execute(()->{try{String rollback=c.getString("rollbackToken","");File[] dirs=transactions().listFiles();if(dirs!=null)for(File d:dirs){if(d.getName().equals(rollback))rollbackDir(d);remove(d);}c.resolve();}catch(Exception e){c.reject(e.getMessage(),e);}});}
 @PluginMethod public void eraseLocal(PluginCall c){getBridge().execute(()->{try{DistanceTrackingService.erase(getContext());if(!new BleWatchPreference(getContext()).clear())throw new IOException("Cannot clear selected watch.");remove(photos());remove(transactions());File backupCache=new File(getContext().getCacheDir(),"backup_export");if(backupCache.exists())remove(backupCache);File[] cache=getContext().getCacheDir().listFiles();if(cache!=null)for(File f:cache)if(f.getName().startsWith("trainpilot-"))remove(f);c.resolve();}catch(Exception e){c.reject(e.getMessage(),e);}});}
 @PluginMethod public void privacy(PluginCall c){Intent i=new Intent(getActivity(),HealthPrivacyActivity.class);i.putExtra("language",c.getString("language","en"));getActivity().startActivity(i);c.resolve();}
}
