package com.repforge.app;

import android.os.OutcomeReceiver;
import android.health.connect.*;
import android.health.connect.changelog.*;
import android.health.connect.datatypes.*;
import android.health.connect.datatypes.Record;
import android.health.connect.datatypes.units.Energy;
import android.health.connect.datatypes.units.Length;
import androidx.annotation.RequiresApi;
import com.getcapacitor.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import org.json.JSONObject;

/** Android 14+ Health Connect record, aggregate and change-log operations. */
@RequiresApi(34)
final class HealthConnectApi34 {
private static final Executor DIRECT=Runnable::run;
private static <T> OutcomeReceiver<T,HealthConnectException> receiver(CompletableFuture<T> f){return new OutcomeReceiver<T,HealthConnectException>(){public void onResult(T v){f.complete(v);}public void onError(HealthConnectException e){f.completeExceptionally(e);}};}
private static Instant[] range(PluginCall c,long maxMinutes){Instant a=Instant.parse(c.getString("start","")),b=Instant.parse(c.getString("end",""));if(!b.isAfter(a)||Duration.between(a,b).toMinutes()>maxMinutes||b.isAfter(Instant.now().plusSeconds(60)))throw new IllegalArgumentException();return new Instant[]{a,b};}
private static Instant[] range(JSObject c,long maxMinutes){Instant a=Instant.parse(c.optString("start","")),b=Instant.parse(c.optString("end",""));if(!b.isAfter(a)||Duration.between(a,b).toMinutes()>maxMinutes||b.isAfter(Instant.now().plusSeconds(60)))throw new IllegalArgumentException();return new Instant[]{a,b};}
private static TimeInstantRangeFilter filter(Instant[] t){return new TimeInstantRangeFilter.Builder().setStartTime(t[0]).setEndTime(t[1]).build();}
private static <T extends Record> List<T> records(HealthBridgePlugin.Access p,HealthConnectManager m,Class<T> type,TimeInstantRangeFilter time)throws Exception{List<T> all=new ArrayList<>();long token=-1;int pages=0;do{p.requireForeground();ReadRecordsRequestUsingFilters.Builder<T> b=new ReadRecordsRequestUsingFilters.Builder<>(type).setTimeRangeFilter(time).setPageSize(1000);if(token!=-1)b.setPageToken(token);CompletableFuture<ReadRecordsResponse<T>> f=new CompletableFuture<>();m.readRecords(b.build(),DIRECT,receiver(f));ReadRecordsResponse<T> r=f.get(30,TimeUnit.SECONDS);all.addAll(r.getRecords());token=r.getNextPageToken();if(++pages>30&&token!=-1)throw new IllegalStateException("Túl sok Health Connect rekordoldal.");}while(token!=-1);return all;}
private static <T extends Record> List<T> safe(HealthBridgePlugin.Access p,HealthConnectManager m,Class<T> type,TimeInstantRangeFilter time,String perm,JSArray warnings){if(!p.allowed(perm))return Collections.emptyList();try{long readAt=System.currentTimeMillis();List<T> result=records(p,m,type,time);p.requireForeground();if(p.epoch!=null)HealthJournalStore.get(p.getContext()).reconcileRecords(HealthConnectJournal.serialize(result,p.getContext().getPackageName()),type.getSimpleName(),time.getStartTime().toEpochMilli(),time.getEndTime().toEpochMilli(),readAt,p.epoch);return p.origin.isEmpty()?result:result.stream().filter(r->src(r).equals(p.origin)).collect(java.util.stream.Collectors.toList());}catch(Exception e){warnings.put(perm+": "+p.message(e));return Collections.emptyList();}}
private static String src(Record r){return r.getMetadata().getDataOrigin().getPackageName();}
private static String id(Record r){return r.getMetadata().getId();}
private static void addSources(Set<String> out,List<? extends Record> rows){for(Record r:rows)out.add(src(r));}
private static JSObject sourceLabels(HealthBridgePlugin.Access p,Set<String> sources){JSObject labels=new JSObject();for(String pkg:sources){try{labels.put(pkg,p.getContext().getPackageManager().getApplicationLabel(p.getContext().getPackageManager().getApplicationInfo(pkg,0)).toString());}catch(Exception ignored){labels.put(pkg,pkg);}}return labels;}
private static <T> T aggregate(HealthBridgePlugin.Access p,HealthConnectManager m,TimeInstantRangeFilter time,AggregationType<T> type)throws Exception{p.requireForeground();AggregateRecordsRequest.Builder<T> builder=new AggregateRecordsRequest.Builder<T>(time).addAggregationType(type);if(!p.origin.isEmpty())builder.addDataOriginsFilter(new DataOrigin.Builder().setPackageName(p.origin).build());AggregateRecordsRequest<T> req=builder.build();CompletableFuture<AggregateRecordsResponse<T>> f=new CompletableFuture<>();m.aggregate(req,DIRECT,receiver(f));return f.get(30,TimeUnit.SECONDS).get(type);}
private static String mostCompleteStepOrigin(HealthBridgePlugin.Access p,HealthConnectManager m,TimeInstantRangeFilter time,Set<String> origins){
 if(!p.allowed("READ_STEPS")||origins.isEmpty())return "";
 String original=p.origin;Map<String,Long> totals=new HashMap<>();
 try{
  for(String origin:new TreeSet<>(origins)){
   if(origin==null||origin.isEmpty()||origin.equals(p.getContext().getPackageName()))continue;
   p.origin=origin;
   try{Long value=aggregate(p,m,time,StepsRecord.STEPS_COUNT_TOTAL);if(value!=null)totals.put(origin,value);}catch(Exception ignored){}
  }
 }finally{p.origin=original;}
 return HealthDailySource.mostComplete(totals);
}
private static void putLongAgg(JSObject out,String key,HealthBridgePlugin.Access p,HealthConnectManager m,TimeInstantRangeFilter time,String perm,AggregationType<Long> type,JSArray warnings){if(!p.allowed(perm)){out.put(key,JSONObject.NULL);return;}try{Long v=aggregate(p,m,time,type);out.put(key,v==null?JSONObject.NULL:v);}catch(Exception e){out.put(key,JSONObject.NULL);warnings.put(perm+": "+p.message(e));}}
private static void putEnergyAgg(JSObject out,String key,HealthBridgePlugin.Access p,HealthConnectManager m,TimeInstantRangeFilter time,String perm,AggregationType<Energy> type,JSArray warnings){if(!p.allowed(perm)){out.put(key,JSONObject.NULL);return;}try{Energy v=aggregate(p,m,time,type);out.put(key,v==null?JSONObject.NULL:v.getInCalories()/1000.0);}catch(Exception e){out.put(key,JSONObject.NULL);warnings.put(perm+": "+p.message(e));}}
private static void putDistanceAgg(JSObject out,HealthBridgePlugin.Access p,HealthConnectManager m,TimeInstantRangeFilter time,JSArray warnings){if(!p.allowed("READ_DISTANCE")){out.put("distanceMeters",JSONObject.NULL);return;}try{Length v=aggregate(p,m,time,DistanceRecord.DISTANCE_TOTAL);out.put("distanceMeters",v==null?JSONObject.NULL:v.getInMeters());}catch(Exception e){out.put("distanceMeters",JSONObject.NULL);warnings.put("READ_DISTANCE: "+p.message(e));}}
private static JSArray sessionArray(List<ExerciseSessionRecord> rows){JSArray a=new JSArray();for(ExerciseSessionRecord r:rows){JSObject x=new JSObject();x.put("id",id(r));x.put("start",r.getStartTime().toString());x.put("end",r.getEndTime().toString());x.put("durationMinutes",Math.max(0,Duration.between(r.getStartTime(),r.getEndTime()).toMinutes()));x.put("exerciseType",r.getExerciseType());x.put("title",r.getTitle()==null?"":r.getTitle().toString());x.put("source",src(r));x.put("clientRecordId",r.getMetadata().getClientRecordId());a.put(x);}return a;}
private static boolean asleepStage(int t){return t==SleepSessionRecord.StageType.STAGE_TYPE_SLEEPING||t==SleepSessionRecord.StageType.STAGE_TYPE_SLEEPING_LIGHT||t==SleepSessionRecord.StageType.STAGE_TYPE_SLEEPING_DEEP||t==SleepSessionRecord.StageType.STAGE_TYPE_SLEEPING_REM;}
private static JSArray sleepArray(List<SleepSessionRecord> rows){JSArray a=new JSArray();for(SleepSessionRecord r:rows){JSObject x=new JSObject();x.put("id",id(r));x.put("start",r.getStartTime().toString());x.put("end",r.getEndTime().toString());x.put("durationMinutes",Math.max(0,Duration.between(r.getStartTime(),r.getEndTime()).toMinutes()));x.put("source",src(r));JSArray stages=new JSArray();for(SleepSessionRecord.Stage s:r.getStages()){JSObject q=new JSObject();q.put("start",s.getStartTime().toString());q.put("end",s.getEndTime().toString());q.put("type",s.getType());q.put("isAsleep",asleepStage(s.getType()));stages.put(q);}x.put("stages",stages);a.put(x);}return a;}
private static void speedStats(JSObject out,List<SpeedRecord> rows,Instant[] t){double sum=0,max=0;int n=0;for(SpeedRecord r:rows)for(SpeedRecord.SpeedRecordSample s:r.getSamples())if(!s.getTime().isBefore(t[0])&&s.getTime().isBefore(t[1])){double v=s.getSpeed().getInMetersPerSecond();if(Double.isFinite(v)&&v>=0){sum+=v;max=Math.max(max,v);n++;}}out.put("averageSpeedMps",n>0?sum/n:JSONObject.NULL);out.put("maxSpeedMps",n>0?max:JSONObject.NULL);out.put("speedSamples",n);}
private static JSObject base(HealthBridgePlugin.Access p,JSArray warnings,Set<String> sources){JSObject out=new JSObject();out.put("warnings",warnings);out.put("permissions",p.permissionStatus());out.put("sources",new JSArray(new ArrayList<>(sources)));out.put("sourceLabels",sourceLabels(p,sources));return out;}

// Aggregate without a DataOrigin filter: Health Connect applies source priority/deduplication.
// A missing value remains null; it is neither a daily total nor a GPS-distance estimate.
static JSObject readStepsWindow(HealthBridgePlugin.Access p,PluginCall c)throws Exception{
 Instant[] t=range(c,24*60);HealthConnectManager m=p.getContext().getSystemService(HealthConnectManager.class);JSArray warnings=new JSArray();JSObject out=base(p,warnings,Collections.emptySet());
 out.put("start",t[0].toString());out.put("end",t[1].toString());
 putLongAgg(out,"steps",p,m,filter(t),"READ_STEPS",StepsRecord.STEPS_COUNT_TOTAL,warnings);return out;
}

static JSObject readTrainingWindow(HealthBridgePlugin.Access p,PluginCall c)throws Exception{
 Instant[] t=range(c,24*60);HealthConnectManager m=p.getContext().getSystemService(HealthConnectManager.class);TimeInstantRangeFilter time=filter(t);if(!p.anyReadAllowed())throw new SecurityException();JSArray warnings=new JSArray();
 List<HeartRateRecord> hrs=safe(p,m,HeartRateRecord.class,time,"READ_HEART_RATE",warnings);List<ExerciseSessionRecord> sessions=safe(p,m,ExerciseSessionRecord.class,time,"READ_EXERCISE",warnings);List<SpeedRecord> speeds=safe(p,m,SpeedRecord.class,time,"READ_SPEED",warnings);List<DistanceRecord> distances=safe(p,m,DistanceRecord.class,time,"READ_DISTANCE",warnings);List<ActiveCaloriesBurnedRecord> active=safe(p,m,ActiveCaloriesBurnedRecord.class,time,"READ_ACTIVE_CALORIES_BURNED",warnings);List<TotalCaloriesBurnedRecord> total=safe(p,m,TotalCaloriesBurnedRecord.class,time,"READ_TOTAL_CALORIES_BURNED",warnings);
 Set<String> sources=new TreeSet<>();addSources(sources,hrs);addSources(sources,sessions);addSources(sources,speeds);addSources(sources,distances);addSources(sources,active);addSources(sources,total);sources.remove(p.getContext().getPackageName());JSObject out=base(p,warnings,sources);out.put("start",t[0].toString());out.put("end",t[1].toString());
 putLongAgg(out,"steps",p,m,time,"READ_STEPS",StepsRecord.STEPS_COUNT_TOTAL,warnings);
 putLongAgg(out,"averageHeartRate",p,m,time,"READ_HEART_RATE",HeartRateRecord.BPM_AVG,warnings);putLongAgg(out,"minHeartRate",p,m,time,"READ_HEART_RATE",HeartRateRecord.BPM_MIN,warnings);putLongAgg(out,"maxHeartRate",p,m,time,"READ_HEART_RATE",HeartRateRecord.BPM_MAX,warnings);putLongAgg(out,"heartRateSamples",p,m,time,"READ_HEART_RATE",HeartRateRecord.HEART_MEASUREMENTS_COUNT,warnings);
 putEnergyAgg(out,"activeCalories",p,m,time,"READ_ACTIVE_CALORIES_BURNED",ActiveCaloriesBurnedRecord.ACTIVE_CALORIES_TOTAL,warnings);putEnergyAgg(out,"totalCalories",p,m,time,"READ_TOTAL_CALORIES_BURNED",TotalCaloriesBurnedRecord.ENERGY_TOTAL,warnings);putDistanceAgg(out,p,m,time,warnings);speedStats(out,speeds,t);out.put("exerciseSessions",sessionArray(sessions));out.put("exerciseSessionCount",sessions.size());long mins=0;for(ExerciseSessionRecord r:sessions)mins+=Math.max(0,Duration.between(r.getStartTime(),r.getEndTime()).toMinutes());out.put("exerciseMinutes",mins);return out;
}

static JSObject readHealthDay(HealthBridgePlugin.Access p,JSObject c)throws Exception{
 Instant[] t=range(c,36*60);p.origin=c.optString("origin","");if(!p.origin.isEmpty()&&!p.origin.matches("[A-Za-z0-9_.-]{1,255}"))throw new IllegalArgumentException("Invalid Health Connect origin");HealthConnectManager m=p.getContext().getSystemService(HealthConnectManager.class);TimeInstantRangeFilter time=filter(t);if(!p.anyReadAllowed())throw new SecurityException();JSArray warnings=new JSArray();
 List<HeartRateRecord> hrs=safe(p,m,HeartRateRecord.class,time,"READ_HEART_RATE",warnings);List<RestingHeartRateRecord> resting=safe(p,m,RestingHeartRateRecord.class,time,"READ_RESTING_HEART_RATE",warnings);List<ExerciseSessionRecord> sessions=safe(p,m,ExerciseSessionRecord.class,time,"READ_EXERCISE",warnings);List<SleepSessionRecord> sleeps=safe(p,m,SleepSessionRecord.class,time,"READ_SLEEP",warnings);List<HeartRateVariabilityRmssdRecord> hrvs=safe(p,m,HeartRateVariabilityRmssdRecord.class,time,"READ_HEART_RATE_VARIABILITY",warnings);List<WeightRecord> weights=safe(p,m,WeightRecord.class,time,"READ_WEIGHT",warnings);List<BodyFatRecord> fats=safe(p,m,BodyFatRecord.class,time,"READ_BODY_FAT",warnings);List<OxygenSaturationRecord> oxy=safe(p,m,OxygenSaturationRecord.class,time,"READ_OXYGEN_SATURATION",warnings);List<Vo2MaxRecord> vo2=safe(p,m,Vo2MaxRecord.class,time,"READ_VO2_MAX",warnings);List<SpeedRecord> speeds=safe(p,m,SpeedRecord.class,time,"READ_SPEED",warnings);List<DistanceRecord> distances=safe(p,m,DistanceRecord.class,time,"READ_DISTANCE",warnings);List<ActiveCaloriesBurnedRecord> active=safe(p,m,ActiveCaloriesBurnedRecord.class,time,"READ_ACTIVE_CALORIES_BURNED",warnings);List<TotalCaloriesBurnedRecord> total=safe(p,m,TotalCaloriesBurnedRecord.class,time,"READ_TOTAL_CALORIES_BURNED",warnings);List<BloodPressureRecord> pressures=safe(p,m,BloodPressureRecord.class,time,"READ_BLOOD_PRESSURE",warnings);List<BloodGlucoseRecord> glucose=safe(p,m,BloodGlucoseRecord.class,time,"READ_BLOOD_GLUCOSE",warnings);List<RespiratoryRateRecord> respiratory=safe(p,m,RespiratoryRateRecord.class,time,"READ_RESPIRATORY_RATE",warnings);
 List<StepsRecord> steps=safe(p,m,StepsRecord.class,time,"READ_STEPS",warnings);
 Set<String> sources=new TreeSet<>();for(List<? extends Record> rows:Arrays.asList(steps,hrs,resting,sessions,sleeps,hrvs,weights,fats,oxy,vo2,speeds,distances,active,total,pressures,glucose,respiratory))addSources(sources,rows);sources.remove(p.getContext().getPackageName());JSObject out=base(p,warnings,sources);out.put("start",t[0].toString());out.put("end",t[1].toString());
 String requested=p.origin;String preferred=HealthJournalStore.get(p.getContext()).preferences().optString("hcDailySource","auto");Set<String> stepOrigins=steps.stream().map(HealthConnectApi34::src).collect(java.util.stream.Collectors.toSet());String activityOrigin=HealthDailySource.choose(requested,preferred,stepOrigins);if(requested.isEmpty()&&"auto".equals(preferred)){String complete=mostCompleteStepOrigin(p,m,time,stepOrigins);if(!complete.isEmpty())activityOrigin=complete;}p.origin=activityOrigin;putLongAgg(out,"steps",p,m,time,"READ_STEPS",StepsRecord.STEPS_COUNT_TOTAL,warnings);p.origin=requested;putLongAgg(out,"averageHeartRate",p,m,time,"READ_HEART_RATE",HeartRateRecord.BPM_AVG,warnings);putLongAgg(out,"minHeartRate",p,m,time,"READ_HEART_RATE",HeartRateRecord.BPM_MIN,warnings);putLongAgg(out,"maxHeartRate",p,m,time,"READ_HEART_RATE",HeartRateRecord.BPM_MAX,warnings);putLongAgg(out,"heartRateSamples",p,m,time,"READ_HEART_RATE",HeartRateRecord.HEART_MEASUREMENTS_COUNT,warnings);putLongAgg(out,"restingHeartRate",p,m,time,"READ_RESTING_HEART_RATE",RestingHeartRateRecord.BPM_AVG,warnings);p.origin=activityOrigin;putEnergyAgg(out,"activeCalories",p,m,time,"READ_ACTIVE_CALORIES_BURNED",ActiveCaloriesBurnedRecord.ACTIVE_CALORIES_TOTAL,warnings);putEnergyAgg(out,"totalCalories",p,m,time,"READ_TOTAL_CALORIES_BURNED",TotalCaloriesBurnedRecord.ENERGY_TOTAL,warnings);putDistanceAgg(out,p,m,time,warnings);p.origin=requested;out.put("activityOrigin",activityOrigin);out.put("aggregateOrigin",requested.isEmpty()?("auto".equals(preferred)&&!activityOrigin.isEmpty()?"health_connect_most_complete_steps":"health_connect_priority"):"health_connect_source");out.put("source",requested.isEmpty()?"@aggregate":requested);out.put("availableStepOrigins",new JSArray(new ArrayList<>(steps.stream().map(HealthConnectApi34::src).collect(java.util.stream.Collectors.toSet()))));speedStats(out,speeds,t);out.put("sleepSessions",sleepArray(sleeps));out.put("exerciseSessions",sessionArray(sessions));
 HeartRateVariabilityRmssdRecord hrv=latestInstant(hrvs);out.put("hrvRmssdMs",hrv==null?JSONObject.NULL:hrv.getHeartRateVariabilityMillis());if(hrv!=null){out.put("hrvTime",hrv.getTime().toString());out.put("hrvSource",src(hrv));out.put("hrvId",id(hrv));}
 WeightRecord w=latestInstant(weights);out.put("weightKg",w==null?JSONObject.NULL:w.getWeight().getInGrams()/1000.0);if(w!=null){out.put("weightTime",w.getTime().toString());out.put("weightSource",src(w));out.put("weightId",id(w));}
 BodyFatRecord fat=latestInstant(fats);out.put("bodyFatPercent",fat==null?JSONObject.NULL:fat.getPercentage().getValue());if(fat!=null){out.put("bodyFatTime",fat.getTime().toString());out.put("bodyFatSource",src(fat));out.put("bodyFatId",id(fat));}
 OxygenSaturationRecord o=latestInstant(oxy);out.put("oxygenSaturationPercent",o==null?JSONObject.NULL:o.getPercentage().getValue());if(o!=null){out.put("oxygenSaturationTime",o.getTime().toString());out.put("oxygenSaturationSource",src(o));out.put("oxygenSaturationId",id(o));}
 Vo2MaxRecord v=latestInstant(vo2);out.put("vo2Max",v==null?JSONObject.NULL:v.getVo2MillilitersPerMinuteKilogram());if(v!=null){out.put("vo2MaxTime",v.getTime().toString());out.put("vo2MaxSource",src(v));out.put("vo2MaxId",id(v));out.put("vo2MaxMeasurementMethod",v.getMeasurementMethod());}
 BloodPressureRecord bp=latestInstant(pressures);out.put("bloodPressureSystolic",bp==null?JSONObject.NULL:bp.getSystolic().getInMillimetersOfMercury());out.put("bloodPressureDiastolic",bp==null?JSONObject.NULL:bp.getDiastolic().getInMillimetersOfMercury());if(bp!=null){out.put("bloodPressureTime",bp.getTime().toString());out.put("bloodPressureSource",src(bp));out.put("bloodPressureId",id(bp));}
 BloodGlucoseRecord bg=latestInstant(glucose);out.put("bloodGlucoseMmolL",bg==null?JSONObject.NULL:bg.getLevel().getInMillimolesPerLiter());if(bg!=null){out.put("bloodGlucoseTime",bg.getTime().toString());out.put("bloodGlucoseSource",src(bg));out.put("bloodGlucoseId",id(bg));}
 RespiratoryRateRecord rr=latestInstant(respiratory);out.put("respiratoryRate",rr==null?JSONObject.NULL:rr.getRate());if(rr!=null){out.put("respiratoryRateTime",rr.getTime().toString());out.put("respiratoryRateSource",src(rr));out.put("respiratoryRateId",id(rr));}
 p.requireForeground();out.put("readAt",Instant.now().toString());HealthJournalStore.get(p.getContext()).healthDay(HealthJournalStore.day(t[0].toEpochMilli()),out,p.epoch);return out;
}
static void sourceDays(HealthBridgePlugin.Access p,String from,String to,String origin)throws Exception {
 if(!origin.matches("[A-Za-z0-9_.-]{1,255}"))throw new IllegalArgumentException("Invalid origin");
 LocalDate a=LocalDate.parse(from),b=LocalDate.parse(to);if(b.isBefore(a)||java.time.temporal.ChronoUnit.DAYS.between(a,b)>30)throw new IllegalArgumentException("Choose up to 31 days for a source summary");
 HealthJournalStore store=HealthJournalStore.get(p.getContext());HealthConnectManager manager=p.getContext().getSystemService(HealthConnectManager.class);p.origin=origin;
 for(LocalDate d=b;!d.isBefore(a);d=d.minusDays(1)){
  p.requireForeground();if(!store.needsSourceDay(d.toString(),origin))continue;
  Instant start=d.atStartOfDay(ZoneId.systemDefault()).toInstant(),end=d.plusDays(1).atStartOfDay(ZoneId.systemDefault()).toInstant();if(end.isAfter(Instant.now()))end=Instant.now();if(!end.isAfter(start))continue;
  TimeInstantRangeFilter time=filter(new Instant[]{start,end});JSObject out=JSObject.fromJSONObject(store.sourceDaySeed(d.toString(),origin));JSArray warnings=new JSArray();
  AggregateRecordsRequest.Builder<Long> counts=new AggregateRecordsRequest.Builder<Long>(time).addDataOriginsFilter(new DataOrigin.Builder().setPackageName(origin).build());
  Map<String,AggregationType<Long>> longTypes=new LinkedHashMap<>();
  if(p.allowed("READ_STEPS"))longTypes.put("steps",StepsRecord.STEPS_COUNT_TOTAL);
  if(p.allowed("READ_HEART_RATE")){longTypes.put("averageHeartRate",HeartRateRecord.BPM_AVG);longTypes.put("minHeartRate",HeartRateRecord.BPM_MIN);longTypes.put("maxHeartRate",HeartRateRecord.BPM_MAX);longTypes.put("heartRateSamples",HeartRateRecord.HEART_MEASUREMENTS_COUNT);}
  if(p.allowed("READ_RESTING_HEART_RATE"))longTypes.put("restingHeartRate",RestingHeartRateRecord.BPM_AVG);
  if(!longTypes.isEmpty()){for(AggregationType<Long> type:longTypes.values())counts.addAggregationType(type);CompletableFuture<AggregateRecordsResponse<Long>> f=new CompletableFuture<>();manager.aggregate(counts.build(),DIRECT,receiver(f));AggregateRecordsResponse<Long> response=f.get(30,TimeUnit.SECONDS);for(Map.Entry<String,AggregationType<Long>> e:longTypes.entrySet())out.put(e.getKey(),response.get(e.getValue())==null?JSONObject.NULL:response.get(e.getValue()));}
  p.requireForeground();putEnergyAgg(out,"activeCalories",p,manager,time,"READ_ACTIVE_CALORIES_BURNED",ActiveCaloriesBurnedRecord.ACTIVE_CALORIES_TOTAL,warnings);putEnergyAgg(out,"totalCalories",p,manager,time,"READ_TOTAL_CALORIES_BURNED",TotalCaloriesBurnedRecord.ENERGY_TOTAL,warnings);putDistanceAgg(out,p,manager,time,warnings);
  p.requireForeground();out.put("source",origin);out.put("activityOrigin",origin);out.put("aggregateOrigin","health_connect_source");out.put("warnings",warnings);out.put("readAt",Instant.now().toString());store.healthDay(d.toString(),out,p.epoch);
 }
}
private static <T extends InstantRecord> T latestInstant(List<T> rows){T best=null;for(T r:rows)if(best==null||r.getTime().isAfter(best.getTime()))best=r;return best;}

static JSObject readRecovery(HealthBridgePlugin.Access p,PluginCall c)throws Exception{
 Instant[] t=range(c,14*24*60);HealthConnectManager m=p.getContext().getSystemService(HealthConnectManager.class);TimeInstantRangeFilter time=filter(t);JSArray warnings=new JSArray();List<SleepSessionRecord> sleeps=safe(p,m,SleepSessionRecord.class,time,"READ_SLEEP",warnings);List<HeartRateVariabilityRmssdRecord> hrvs=safe(p,m,HeartRateVariabilityRmssdRecord.class,time,"READ_HEART_RATE_VARIABILITY",warnings);SleepSessionRecord sleep=null;for(SleepSessionRecord r:sleeps)if(sleep==null||r.getEndTime().isAfter(sleep.getEndTime()))sleep=r;HeartRateVariabilityRmssdRecord latest=latestInstant(hrvs);List<Double> vals=new ArrayList<>();for(HeartRateVariabilityRmssdRecord r:hrvs){double v=r.getHeartRateVariabilityMillis();if(v>0&&Double.isFinite(v))vals.add(v);}Collections.sort(vals);Double med=null;if(!vals.isEmpty()){int n=vals.size();med=n%2==1?vals.get(n/2):(vals.get(n/2-1)+vals.get(n/2))/2.0;}JSObject out=new JSObject();out.put("warnings",warnings);out.put("permissions",p.permissionStatus());out.put("sleepMinutes",sleep==null?JSONObject.NULL:Math.max(0,Duration.between(sleep.getStartTime(),sleep.getEndTime()).toMinutes()));out.put("sleepStart",sleep==null?JSONObject.NULL:sleep.getStartTime().toString());out.put("sleepEnd",sleep==null?JSONObject.NULL:sleep.getEndTime().toString());if(sleep!=null)out.put("sleepSource",src(sleep));out.put("hrvRmssdMs",latest==null?JSONObject.NULL:latest.getHeartRateVariabilityMillis());out.put("hrvBaselineMs",med==null?JSONObject.NULL:med);out.put("hrvSamples",vals.size());if(latest!=null)out.put("hrvSource",src(latest));return out;
}
static JSObject readWellness(HealthBridgePlugin.Access p,PluginCall c)throws Exception{Instant[] t=range(c,14*24*60);PluginCall fake=c;JSObject day=readHealthDayRange(p,t);JSObject out=new JSObject();for(String k:new String[]{"steps","weightKg","weightTime","weightSource","bodyFatPercent","bodyFatTime","bodyFatSource","oxygenSaturationPercent","oxygenSaturationTime","oxygenSaturationSource","vo2Max","vo2MaxTime","vo2MaxSource","vo2MaxMeasurementMethod","warnings","permissions"})if(day.has(k))out.put(k,day.get(k));return out;}
private static JSObject readHealthDayRange(HealthBridgePlugin.Access p,Instant[] t)throws Exception{HealthConnectManager m=p.getContext().getSystemService(HealthConnectManager.class);TimeInstantRangeFilter time=filter(t);JSArray warnings=new JSArray();JSObject out=new JSObject();putLongAgg(out,"steps",p,m,time,"READ_STEPS",StepsRecord.STEPS_COUNT_TOTAL,warnings);List<WeightRecord> weights=safe(p,m,WeightRecord.class,time,"READ_WEIGHT",warnings);List<BodyFatRecord> fats=safe(p,m,BodyFatRecord.class,time,"READ_BODY_FAT",warnings);List<OxygenSaturationRecord> oxy=safe(p,m,OxygenSaturationRecord.class,time,"READ_OXYGEN_SATURATION",warnings);List<Vo2MaxRecord> vo2=safe(p,m,Vo2MaxRecord.class,time,"READ_VO2_MAX",warnings);WeightRecord w=latestInstant(weights);BodyFatRecord f=latestInstant(fats);OxygenSaturationRecord o=latestInstant(oxy);Vo2MaxRecord v=latestInstant(vo2);out.put("weightKg",w==null?JSONObject.NULL:w.getWeight().getInGrams()/1000.0);if(w!=null){out.put("weightTime",w.getTime().toString());out.put("weightSource",src(w));}out.put("bodyFatPercent",f==null?JSONObject.NULL:f.getPercentage().getValue());if(f!=null){out.put("bodyFatTime",f.getTime().toString());out.put("bodyFatSource",src(f));}out.put("oxygenSaturationPercent",o==null?JSONObject.NULL:o.getPercentage().getValue());if(o!=null){out.put("oxygenSaturationTime",o.getTime().toString());out.put("oxygenSaturationSource",src(o));}out.put("vo2Max",v==null?JSONObject.NULL:v.getVo2MillilitersPerMinuteKilogram());if(v!=null){out.put("vo2MaxTime",v.getTime().toString());out.put("vo2MaxSource",src(v));out.put("vo2MaxMeasurementMethod",v.getMeasurementMethod());}out.put("warnings",warnings);out.put("permissions",p.permissionStatus());return out;}

private static void addGrantedTypes(HealthBridgePlugin.Access p,ChangeLogTokenRequest.Builder b){if(p.allowed("READ_HEART_RATE"))b.addRecordType(HeartRateRecord.class);if(p.allowed("READ_RESTING_HEART_RATE"))b.addRecordType(RestingHeartRateRecord.class);if(p.allowed("READ_ACTIVE_CALORIES_BURNED"))b.addRecordType(ActiveCaloriesBurnedRecord.class);if(p.allowed("READ_TOTAL_CALORIES_BURNED"))b.addRecordType(TotalCaloriesBurnedRecord.class);if(p.allowed("READ_EXERCISE"))b.addRecordType(ExerciseSessionRecord.class);if(p.allowed("READ_SLEEP"))b.addRecordType(SleepSessionRecord.class);if(p.allowed("READ_HEART_RATE_VARIABILITY"))b.addRecordType(HeartRateVariabilityRmssdRecord.class);if(p.allowed("READ_STEPS"))b.addRecordType(StepsRecord.class);if(p.allowed("READ_WEIGHT"))b.addRecordType(WeightRecord.class);if(p.allowed("READ_BODY_FAT"))b.addRecordType(BodyFatRecord.class);if(p.allowed("READ_OXYGEN_SATURATION"))b.addRecordType(OxygenSaturationRecord.class);if(p.allowed("READ_VO2_MAX"))b.addRecordType(Vo2MaxRecord.class);if(p.allowed("READ_DISTANCE"))b.addRecordType(DistanceRecord.class);if(p.allowed("READ_SPEED"))b.addRecordType(SpeedRecord.class);if(p.allowed("READ_BLOOD_PRESSURE"))b.addRecordType(BloodPressureRecord.class);if(p.allowed("READ_BLOOD_GLUCOSE"))b.addRecordType(BloodGlucoseRecord.class);if(p.allowed("READ_RESPIRATORY_RATE"))b.addRecordType(RespiratoryRateRecord.class);}
private static void addNamedType(HealthBridgePlugin.Access p,ChangeLogTokenRequest.Builder b,String type){switch(type){case "HeartRateRecord":if(p.allowed("READ_HEART_RATE"))b.addRecordType(HeartRateRecord.class);break;case "RestingHeartRateRecord":if(p.allowed("READ_RESTING_HEART_RATE"))b.addRecordType(RestingHeartRateRecord.class);break;case "ActiveCaloriesBurnedRecord":if(p.allowed("READ_ACTIVE_CALORIES_BURNED"))b.addRecordType(ActiveCaloriesBurnedRecord.class);break;case "TotalCaloriesBurnedRecord":if(p.allowed("READ_TOTAL_CALORIES_BURNED"))b.addRecordType(TotalCaloriesBurnedRecord.class);break;case "ExerciseSessionRecord":if(p.allowed("READ_EXERCISE"))b.addRecordType(ExerciseSessionRecord.class);break;case "SleepSessionRecord":if(p.allowed("READ_SLEEP"))b.addRecordType(SleepSessionRecord.class);break;case "HeartRateVariabilityRmssdRecord":if(p.allowed("READ_HEART_RATE_VARIABILITY"))b.addRecordType(HeartRateVariabilityRmssdRecord.class);break;case "StepsRecord":if(p.allowed("READ_STEPS"))b.addRecordType(StepsRecord.class);break;case "WeightRecord":if(p.allowed("READ_WEIGHT"))b.addRecordType(WeightRecord.class);break;case "BodyFatRecord":if(p.allowed("READ_BODY_FAT"))b.addRecordType(BodyFatRecord.class);break;case "OxygenSaturationRecord":if(p.allowed("READ_OXYGEN_SATURATION"))b.addRecordType(OxygenSaturationRecord.class);break;case "Vo2MaxRecord":if(p.allowed("READ_VO2_MAX"))b.addRecordType(Vo2MaxRecord.class);break;case "DistanceRecord":if(p.allowed("READ_DISTANCE"))b.addRecordType(DistanceRecord.class);break;case "SpeedRecord":if(p.allowed("READ_SPEED"))b.addRecordType(SpeedRecord.class);break;case "BloodPressureRecord":if(p.allowed("READ_BLOOD_PRESSURE"))b.addRecordType(BloodPressureRecord.class);break;case "BloodGlucoseRecord":if(p.allowed("READ_BLOOD_GLUCOSE"))b.addRecordType(BloodGlucoseRecord.class);break;case "RespiratoryRateRecord":if(p.allowed("READ_RESPIRATORY_RATE"))b.addRecordType(RespiratoryRateRecord.class);break;default:throw new IllegalArgumentException("Ismeretlen Health Connect rekordtípus: "+type);}}
static JSObject createChangeToken(HealthBridgePlugin.Access p,PluginCall c)throws Exception{if(!p.anyReadAllowed())throw new SecurityException();ChangeLogTokenRequest.Builder b=new ChangeLogTokenRequest.Builder();String type=c.getString("recordType","");if(type!=null&&!type.isEmpty())addNamedType(p,b,type);else addGrantedTypes(p,b);CompletableFuture<ChangeLogTokenResponse> f=new CompletableFuture<>();p.getContext().getSystemService(HealthConnectManager.class).getChangeLogToken(b.build(),DIRECT,receiver(f));ChangeLogTokenResponse r=f.get(30,TimeUnit.SECONDS);JSObject out=new JSObject();out.put("token",r.getToken());out.put("createdAt",Instant.now().toString());return out;}
private static void addDay(Set<String> days,Instant time){days.add(time.atZone(ZoneId.systemDefault()).toLocalDate().toString());}
private static void addRecordDays(Set<String> days,Record r){if(r instanceof InstantRecord)addDay(days,((InstantRecord)r).getTime());else if(r instanceof IntervalRecord){Instant a=((IntervalRecord)r).getStartTime(),b=((IntervalRecord)r).getEndTime();LocalDate d=a.atZone(ZoneId.systemDefault()).toLocalDate(),e=b.atZone(ZoneId.systemDefault()).toLocalDate();while(!d.isAfter(e)){days.add(d.toString());d=d.plusDays(1);}}}
static JSObject pollChanges(HealthBridgePlugin.Access p,PluginCall c)throws Exception{String token=c.getString("token","");if(token==null||token.isEmpty())throw new IllegalArgumentException();HealthConnectManager m=p.getContext().getSystemService(HealthConnectManager.class);Set<String> days=new TreeSet<>(),types=new TreeSet<>();int deleted=0,pages=0;String next=token;boolean more;do{p.requireForeground();CompletableFuture<ChangeLogsResponse> f=new CompletableFuture<>();m.getChangeLogs(new ChangeLogsRequest.Builder(next).setPageSize(2000).build(),DIRECT,receiver(f));ChangeLogsResponse r=f.get(30,TimeUnit.SECONDS);for(Record x:r.getUpsertedRecords()){if(src(x).equals(p.getContext().getPackageName()))continue;types.add(x.getClass().getSimpleName());addRecordDays(days,x);}org.json.JSONArray deletedRecords=new org.json.JSONArray();for(ChangeLogsResponse.DeletedLog d:r.getDeletedLogs())deletedRecords.put(new JSONObject().put("recordId",d.getDeletedRecordId()).put("deletedMs",d.getDeletedTime().toEpochMilli()));org.json.JSONArray dirty=HealthJournalStore.get(p.getContext()).applyChanges(HealthConnectJournal.serialize(r.getUpsertedRecords(),p.getContext().getPackageName()),deletedRecords,p.epoch);for(int i=0;i<dirty.length();i++)days.add(dirty.getString(i));deleted+=r.getDeletedLogs().size();next=r.getNextChangesToken();more=r.hasMorePages();if(++pages>20&&more)throw new IllegalStateException("Túl sok változásoldal.");}while(more);JSObject out=new JSObject();out.put("changedDays",new JSArray(new ArrayList<>(days)));out.put("changedTypes",new JSArray(new ArrayList<>(types)));out.put("deletedCount",deleted);out.put("nextToken",next);out.put("checkedAt",Instant.now().toString());return out;}

static void write(HealthBridgePlugin.Access p,PluginCall c)throws Exception{Instant[] t=range(c,24*60);String clientRecordId=c.getString("clientRecordId","");if(clientRecordId==null||clientRecordId.isEmpty())clientRecordId="trainpilot:"+t[0];Metadata meta=new Metadata.Builder().setClientRecordId(clientRecordId).setClientRecordVersion(Math.max(1L,c.getData().optLong("clientVersion",1L))).setRecordingMethod(Metadata.RECORDING_METHOD_ACTIVELY_RECORDED).build();ExerciseSessionRecord r=new ExerciseSessionRecord.Builder(meta,t[0],t[1],ExerciseSessionType.EXERCISE_SESSION_TYPE_STRENGTH_TRAINING).setTitle(c.getString("title","TrainPilot")).build();CompletableFuture<InsertRecordsResponse> f=new CompletableFuture<>();p.getContext().getSystemService(HealthConnectManager.class).insertRecords(Collections.singletonList(r),DIRECT,receiver(f));f.get(30,TimeUnit.SECONDS);}
 }
}
