const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const values=new Map(),alerts=[];let accept=true,failKey=null,reply={cancelled:true};
const ctx=vm.createContext({localStorage:{getItem:k=>values.get(k)??null,setItem:(k,v)=>{if(k===failKey){failKey=null;throw Error('Quota');}values.set(k,v)},removeItem:k=>values.delete(k)},document:{querySelector:()=>({innerHTML:'',remove(){}}),getElementById:()=>null,addEventListener(){}},window:{Capacitor:{isNativePlatform:()=>true,registerPlugin:()=>({save:async()=>reply})},scrollTo(){}},navigator:{},setInterval:()=>1,clearInterval(){},Date,alert:t=>alerts.push(t),confirm:()=>accept,console});
for(const f of ['backup.js','demos.js','cloud.js','app.js'])vm.runInContext(fs.readFileSync('www/'+f,'utf8'),ctx);
const run=s=>vm.runInContext(s,ctx), snapshot=()=>JSON.stringify([...values].sort());
(async()=>{
 run("startWorkout('B');upd(0,0,'reps','10');toggleSet(0,0)");
 assert.equal(run("db.get('draft').session.exercises[0].sets[0].reps"),'10');
 run('state.session=null;state.workout=null;go("settings");resumeDraft()');
 assert.equal(run('state.workout'),'B');assert.equal(run('state.tab'),'plan');assert.equal(run('state.session.exercises[0].sets[0].done'),true);
 run('finishWorkout()');assert.equal(run("db.get('draft',null)"),null);
 ctx.backup=run('JSON.stringify(makeBackup())');
 assert.equal(run('validateBackup(JSON.parse(backup)).history.length'),1);
 run('let legacy=JSON.parse(backup);legacy.version=1;delete legacy.app;legacy.exercises.forEach(e=>{delete e.loadType;delete e.repUnit});validateBackup(legacy)');
 let before=snapshot();assert.throws(()=>run('restoreText("oops")'));assert.equal(snapshot(),before);
 assert.throws(()=>run('let bad=JSON.parse(backup);bad.plan.A=["missing"];restoreText(JSON.stringify(bad))'));assert.equal(snapshot(),before);
 accept=false;assert.equal(run('restoreText(backup)'),false);assert.equal(snapshot(),before);accept=true;
 failKey='repforge:plan';assert.throws(()=>run('restoreText(backup)'),/tárhely/);assert.equal(snapshot(),before);
 assert.equal(run('restoreText(backup)'),true);
 await run('exportData()');assert.equal(values.has('repforge:lastExport'),false);
 reply={verified:false};await run('exportData()');assert.equal(values.has('repforge:lastExport'),false);assert.match(alerts.at(-1),/Nem készült/);
 reply={verified:true,name:'test.json',bytes:123};await run('exportData()');assert.equal(JSON.parse(values.get('repforge:lastExport')).name,'test.json');
 assert.equal(run('Object.keys(DEMOS).length'),26);assert.equal(run("Object.values(DEMOS).filter(x=>x[1]==='youtube').length"),26);
 run("db.set('exercises',[{id:'reverse-lunge',sets:4,reps:'9/láb',weight:0,loadType:'bodyweight'}]);db.set('lunge114',false)");
 const oldHistory=values.get('repforge:history');run('migrateLunge114()');
 assert.equal(run("byId('reverse-lunge').weight"),5);assert.equal(run("byId('reverse-lunge').sets"),4);
 assert.equal(run("byId('reverse-lunge').loadType"),'per_hand');assert.equal(values.get('repforge:history'),oldHistory);
 run("db.set('exercises',[{id:'reverse-lunge',weight:7,loadType:'per_hand'}]);db.set('lunge114',false);migrateLunge114()");assert.equal(run("byId('reverse-lunge').weight"),7);
 run("db.set('exercises',[{id:'reverse-lunge',weight:0,loadType:'bodyweight'}]);migrateLunge114()");assert.equal(run("byId('reverse-lunge').loadType"),'bodyweight');
 assert.equal(run("demoInfo('db-ohp').provider"),'youtube');assert.equal(run("demoInfo('reverse-lunge').videoId"),'sjlsISvHyZs');
 console.log('PASS: backup validation, invalid JSON/plan rejection, cancelled restore, quota rollback, export cancellation/failure/success, draft resume, video mappings.');
})().catch(e=>{console.error(e);process.exitCode=1});
