const assert=require('node:assert/strict'),fs=require('node:fs');
const app=fs.readFileSync('www/app.js','utf8');
const java=fs.readFileSync('android/app/src/main/java/com/repforge/app/WorkoutPhotosPlugin.java','utf8');
const google=fs.readFileSync('android/app/src/main/java/com/repforge/app/GoogleSyncPlugin.java','utf8');
const manifest=fs.readFileSync('android/app/src/main/AndroidManifest.xml','utf8');
const paths=fs.readFileSync('android/app/src/main/res/xml/file_paths.xml','utf8');
const pkg=require('../package.json'),src=require('../SOURCE_VERSION.json'),gradle=fs.readFileSync('android/app/build.gradle','utf8');
assert.ok(!pkg.dependencies['@capacitor/camera']);
assert.ok(app.includes("source==='capture'?await storage.capture():await storage.pick()"));
assert.ok(java.includes('setPackage("com.miui.gallery")'));
assert.ok(java.includes('Intent.EXTRA_LOCAL_ONLY'));
assert.ok(java.includes('FileProvider.getUriForFile'));
assert.ok(java.includes('File.createTempFile("trainpilot-camera-", ".jpg"'));
assert.ok(java.includes('waitForFileData(outputFile)'));
assert.ok(java.includes('returnedUri != null && uriHasData(returnedUri)'));
assert.ok(java.includes('returnedExtra instanceof Bitmap'));
assert.ok(java.indexOf('waitForFileData(outputFile)')<java.indexOf('resultCode == Activity.RESULT_CANCELED'),'usable camera bytes must win over an OEM RESULT_CANCELED');
assert.ok(!java.includes('createMediaStoreCameraUri'));
assert.ok(!java.includes('cameraUsesMediaStore'));
assert.ok(paths.includes('<cache-path name="trainpilot_camera_cache" path="."'));
assert.ok(manifest.includes('android.media.action.IMAGE_CAPTURE'));
assert.ok(manifest.includes('androidx.core.content.FileProvider'));
assert.ok(!manifest.includes('android.permission.CAMERA'));
assert.ok(!manifest.includes('READ_MEDIA_IMAGES'));
assert.ok(google.includes('ExecutorService ioExecutor')&&google.includes('ioExecutor.submit(()->{try{'));
assert.ok(!google.includes('getBridge().execute(()->{try{'));
assert.equal(pkg.version,'1.0.0');assert.equal(src.version,'1.0.0');assert.equal(src.versionCode,2672);
assert.match(gradle,/versionCode\s+2672/);assert.match(gradle,/versionName\s+"1\.0\.0"/);
console.log('PASS TrainPilot 2672 private FileProvider camera / OEM return fallback / queue isolation guards');
