const assert=require('node:assert/strict'),fs=require('node:fs');
const app=fs.readFileSync('www/app.js','utf8');
const java=fs.readFileSync('android/app/src/main/java/com/repforge/app/WorkoutPhotosPlugin.java','utf8');
const google=fs.readFileSync('android/app/src/main/java/com/repforge/app/GoogleSyncPlugin.java','utf8');
const manifest=fs.readFileSync('android/app/src/main/AndroidManifest.xml','utf8');
const pkg=require('../package.json'),src=require('../SOURCE_VERSION.json'),gradle=fs.readFileSync('android/app/build.gradle','utf8');
assert.ok(!pkg.dependencies['@capacitor/camera']);
assert.ok(app.includes("source==='capture'?await storage.capture():await storage.pick()"));
assert.ok(java.includes('setPackage("com.miui.gallery")'));
assert.ok(java.includes('Intent.EXTRA_LOCAL_ONLY'));
assert.ok(java.includes('MediaStore.Images.Media.RELATIVE_PATH'));
assert.ok(java.includes('MediaStore.Images.Media.IS_PENDING'));
assert.ok(java.includes('deleteCameraMediaStoreUri'));
assert.ok(java.includes('uriHasData'));
assert.ok(manifest.includes('android.media.action.IMAGE_CAPTURE'));
assert.ok(!manifest.includes('android.permission.CAMERA'));
assert.ok(!manifest.includes('READ_MEDIA_IMAGES'));
assert.ok(google.includes('ExecutorService ioExecutor')&&google.includes('ioExecutor.submit(()->{try{'));
assert.ok(!google.includes('getBridge().execute(()->{try{'));
assert.equal(src.versionCode,2661);assert.match(gradle,/versionCode\s+2661/);
console.log('PASS TrainPilot 2661 local gallery / MediaStore camera / queue isolation guards');
