const assert=require('node:assert/strict'),fs=require('node:fs');
const java=fs.readFileSync('android/app/src/main/java/com/repforge/app/WorkoutPhotosPlugin.java','utf8');
const app=fs.existsSync('www/app.js')?fs.readFileSync('www/app.js','utf8'):fs.readdirSync('www').filter(x=>x.endsWith('.js')).map(x=>fs.readFileSync('www/'+x,'utf8')).join('\n'),pkg=require('../package.json'),src=require('../SOURCE_VERSION.json');
const gradle=fs.readFileSync('android/app/build.gradle','utf8'),sw=fs.readFileSync('www/sw.js','utf8');
assert.ok(java.includes('Intent.ACTION_GET_CONTENT'));
assert.ok(java.includes('Intent.EXTRA_LOCAL_ONLY'));
assert.ok(java.includes('setPackage("com.miui.gallery")'));
assert.ok(java.includes('Intent.CATEGORY_OPENABLE'));
assert.ok(java.includes('intent.setType("image/*")'));
assert.ok(!java.includes('MediaStore.ACTION_PICK_IMAGES'));
assert.equal(pkg.version,'1.0.0');assert.equal(src.version,'1.0.0');assert.equal(src.versionCode,2672);
assert.match(gradle,/versionCode\s+2672/);assert.match(gradle,/versionName\s+"1\.0\.0"/);assert.ok(sw.includes('trainpilot-v100-rc2'));
console.log('PASS TrainPilot 2652 local-only gallery picker guards');
