const fs=require('node:fs'),assert=require('node:assert/strict');
const app=fs.existsSync('www/app.js')?fs.readFileSync('www/app.js','utf8'):fs.readdirSync('www').filter(x=>x.endsWith('.js')).map(x=>fs.readFileSync('www/'+x,'utf8')).join('\n');
const java=fs.readFileSync('android/app/src/main/java/com/repforge/app/WorkoutPhotosPlugin.java','utf8');
const google=fs.readFileSync('android/app/src/main/java/com/repforge/app/GoogleSyncPlugin.java','utf8');
const main=fs.readFileSync('android/app/src/main/java/com/repforge/app/MainActivity.java','utf8');
const manifest=fs.readFileSync('android/app/src/main/AndroidManifest.xml','utf8');
const vars=fs.readFileSync('android/variables.gradle','utf8');
const gradle=fs.readFileSync('android/app/build.gradle','utf8');
const rootGradle=fs.readFileSync('android/build.gradle','utf8');
for(const x of ['TP130_VERSION','rf130OpenAddPhoto','rf130AcquirePhoto','rf130SyncWorkoutPhotos','rf130MergeHistoryPhotos','rf130DeletePhoto','rf130ShowPhoto'])assert.ok(app.includes(x),'missing '+x);
assert.ok(app.includes('drivePhotoWrite')||google.includes('drivePhotoWrite'));
for(const x of ['pick','capture','storeDataUrl','read','exists','delete'])assert.ok(java.includes(`void ${x}(`),'missing WorkoutPhotos.'+x);
for(const x of ['drivePhotoWrite','drivePhotoRead','drivePhotoDelete'])assert.ok(google.includes(x),'missing GoogleSync '+x);
assert.ok(main.includes('registerPlugin(WorkoutPhotosPlugin.class)'));
assert.ok(!manifest.includes('READ_MEDIA_IMAGES'),'broad image permission must not be requested');
assert.ok(!manifest.includes('READ_EXTERNAL_STORAGE'),'legacy broad storage permission must not be requested');
assert.ok(java.includes('Intent.ACTION_GET_CONTENT')&&java.includes('Intent.EXTRA_LOCAL_ONLY'),'local-only image picker required');
assert.ok(!java.includes('MediaStore.ACTION_PICK_IMAGES'),'framework Photo Picker must be bypassed after the real-device launch regression');
assert.ok((java.match(/getBridge\(\)\.executeOnMainThread/g)||[]).length>=2,'photo picker and camera must launch on the Android main UI thread');
assert.ok(java.includes('Intent.CATEGORY_OPENABLE')&&java.includes('image/*'),'local picker must be restricted to openable images');
assert.ok(java.includes('ExifInterface')&&java.includes('Bitmap.CompressFormat.JPEG'),'photo normalization must strip original metadata by re-encoding');
assert.ok(vars.includes('compileSdkVersion = 36')&&vars.includes('targetSdkVersion = 36'),'Play 2026 target API 36 required');
assert.ok(gradle.includes('versionCode 2652')&&gradle.includes('versionName "1.6.3"'));
assert.ok(rootGradle.includes("com.android.tools.build:gradle:8.10.1"),'API 36 needs compatible AGP');
assert.ok(app.includes("state.tab='plan';state.workout=d.id"),'every workout start must enter the Workout tab before first render');
assert.ok(app.includes('startWorkout=function(w,scheduleId=null,programId=null){rf152StartWorkout(w,scheduleId,programId);if(!state.session)return;'),'workout wrapper must preserve programId for calendar/direct parity');
console.log('PASS 1.3 workout photos / Drive / Play guards');

assert.ok(!app.includes("event.stopPropagation();rf130OpenAddPhoto"),'photo add button must not depend on implicit global event');
assert.ok(app.includes('data-rf130-source="capture"')&&app.includes("modal.addEventListener('click'"),'photo modal actions must use explicit click binding');
