const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),crypto=require('node:crypto').webcrypto;
const values=new Map(),root={innerHTML:''};
const ls={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};
const doc={querySelector:()=>root,querySelectorAll:()=>[],getElementById:()=>null,addEventListener(){},createElement:()=>({className:'',innerHTML:'',querySelector:()=>({focus(){}})}),body:{appendChild(){}}};
const ctx=vm.createContext({localStorage:ls,document:doc,window:{Capacitor:{isNativePlatform:()=>false},scrollTo(){},open(){}},navigator:{onLine:true},setInterval:()=>1,clearInterval(){},setTimeout:()=>1,clearTimeout(){},Date,crypto,TextEncoder,Blob:function(){},URL:{createObjectURL(){return''},revokeObjectURL(){}},alert(){},confirm:()=>true,prompt:()=>null,console});
for(const f of ['backup.js','demos.js','cloud.js','app.js','v12.js','catalog131.js','v13.js','library131.js','onboarding132.js','v14.js'])vm.runInContext(fs.readFileSync('www/'+f,'utf8'),ctx);
const run=s=>vm.runInContext(s,ctx);
ctx.p={age:28,height:180,weight:80,goal:'fitness',experience:'beginner',activity:'mixed',minutes:45,location:'home',cadence:'alternate',split:'auto',excluded:[],gear:['dumbbells','support']};
assert.equal(run('exercises().length'),40);
assert.equal(run("exercises().every(e=>e.movementPattern&&e.difficulty&&e.complexity&&Array.isArray(e.goalTags))"),true);
assert.equal(run("exercises().filter(e=>e.beginnerSafe).length>=30"),true);
assert.equal(run("generatePersonalProgram(p).generatorVersion"),'1.4.0');
assert.equal(run("generatePersonalProgram(p).days.flatMap(d=>d.exercises).every(id=>available132(id,p))"),true);
assert.equal(run("generatePersonalProgram(p).days.flatMap(d=>d.exercises).every(id=>exercises().find(e=>e.id===id).beginnerSafe)"),true);
ctx.h={programId:'x',exercises:[]};
assert.equal(run("rf14ProgressionSummary(h,'pain').action"),'none');
values.set('repforge:weights',JSON.stringify([{kg:80,date:'2026-09-07T10:00:00Z'},{kg:81,date:'2026-09-08T10:00:00Z'}]));
assert.equal(run('rf14WeeklyWeights()[0].avg'),80.5);
assert.equal(run("rf14Meta({id:'x',hu:'X',en:'X',custom:true}).custom"),true);
assert.equal(run('makeBackup().appVersion'),'1.4.0');
assert.ok(run("rf14Alternatives('db-floor-press',p).some(e=>e.movementPattern==='horizontal-push')"));
console.log('PASS: RepForge 1.4 engine metadata, beginner-safe generator, equipment rules, progression guard, weekly averages, alternatives and backup version.');
values.set('repforge:programs',JSON.stringify([{id:'c1',name:'C',builtin:false,days:[{id:'A',name:'A',exercises:['db-squat','pushup']}]}]));
run("moveCustomExercise14('c1',0,1,-1)");
assert.equal(run("programById('c1').days[0].exercises.join(',')"),'pushup,db-squat');
console.log('PASS: custom-program exercise reordering.');
