const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync('www/v142.js','utf8');
const index=fs.readFileSync('www/index.html','utf8');
const bundle=fs.existsSync('www/trainpilot.bundle.js')?fs.readFileSync('www/trainpilot.bundle.js','utf8'):'';
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const gradle=fs.readFileSync('android/app/build.gradle','utf8');
assert(js.includes("const RF142_VERSION='1.4.2'"),'version constant missing');
assert(js.includes('function editHistoryWorkout'),'history edit UI missing');
assert(js.includes('function saveHistoryWorkoutTime'),'history time save missing');
assert(js.includes('function deleteHistoryWorkout'),'history delete missing');
assert(js.includes('function rf142ReadHealthForWorkout'),'Health Connect reread missing');
assert(js.includes('type="datetime-local"'),'datetime editor missing');
assert(js.includes("status:'planned'"),'scheduled workout reset after history deletion missing');
assert(js.includes("await p.readWorkout({start:h.started,end:h.finished,source})"),'corrected workout window not used for Health Connect');
assert(index.includes('v142.js')||bundle.includes("const RF142_VERSION='1.4.2'"),'v142 layer not loaded in index or consolidated runtime');
const atLeast=(v,a,b,c)=>{const [x=0,y=0,z=0]=String(v).split('.').map(Number);return x>a||(x===a&&(y>b||(y===b&&z>=c)));};
assert.equal(pkg.version,'1.6.6','canonical product version');
const vm=gradle.match(/versionCode\s+(\d+)/);assert(vm&&Number(vm[1])>=142,'versionCode must be 142 or newer');
const vn=gradle.match(/versionName\s+"([^"]+)"/);assert(vn&&vn[1]==='1.6.6','canonical Android versionName');
console.log('PASS v1.4.2 workout time editing, deletion, Health Connect re-read, and consolidated runtime loading');
