const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const values=new Map(),root={innerHTML:''};
const node=()=>({innerHTML:'',style:{setProperty(){}},classList:{add(){},remove(){}},querySelector:()=>null,querySelectorAll:()=>[],appendChild(){},prepend(){},insertAdjacentElement(){},insertAdjacentHTML(){},remove(){},setAttribute(){}});
const doc={querySelector:s=>s==='#app'?root:null,querySelectorAll:()=>[],getElementById:()=>null,addEventListener(){},createElement:node,head:node(),body:node(),documentElement:node()};
const ctx=vm.createContext({localStorage:{getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)},document:doc,window:{Capacitor:{isNativePlatform:()=>false},scrollTo(){},open(){}},navigator:{onLine:true},setInterval:()=>1,clearInterval(){},setTimeout:()=>1,clearTimeout(){},Date,crypto:require('node:crypto').webcrypto,TextEncoder,Blob,URL,alert(){},confirm:()=>true,prompt:()=>null,console});
for(const [,f] of fs.readFileSync('www/index.html','utf8').matchAll(/<script\b[^>]*\bsrc="([^"]+)"[^>]*>/g))vm.runInContext(fs.readFileSync('www/'+f,'utf8'),ctx,{filename:f});
const run=s=>vm.runInContext(s,ctx);

(async()=>{
 const heading=()=>root.innerHTML.match(/<h1>(.*?)<\/h1>/)?.[1];
 run("db.set('language','hu');rf206HealthHub()");const hub=heading();
 run('render()');assert.equal(heading(),hub,'background render must preserve Health');
 run("go('settings');go('health')");assert.equal(heading(),hub,'go health must resolve');
 run('healthScreen()');const details=heading();run('render()');assert.equal(heading(),details);
 run('rf215WeightScreen()');const weight=heading();run('render()');assert.equal(heading(),weight);
 run("go('health')");assert.equal(heading(),hub,'Health tab exits a subpage');
 let resolveRead,held=false;
 const waitRead=async()=>{for(let i=0;!resolveRead&&i<100;i++)await new Promise(r=>setImmediate(r));assert.ok(resolveRead,'pipeline must reach its native day read')};
 ctx.bridge={getStatus:async()=>({permissions:{READ_SLEEP:true}}),requestRead:async()=>({}),createChangeToken:async()=>({token:'test'}),pollChanges:async()=>({nextToken:'test',changedDays:[]}),readHealthDay:()=>held?Promise.resolve({}):new Promise(r=>{held=true;resolveRead=r})};
 run('healthPlugin=()=>bridge');
 let pending=run('rf207ReadTodayHealth()');await waitRead();
 assert.equal(heading(),hub,'read must not open settings');
 assert.equal(run('state.health.busy'),true);
 resolveRead({sources:[],source:'',activeCalories:null});await pending;
 assert.equal(heading(),hub);assert.equal(run('state.health.busy'),false);
 held=false;resolveRead=null;pending=run('rf207ReadTodayHealth()');await waitRead();run("go('programs')");const destination=heading();
 resolveRead({sources:[],source:''});await pending;
 assert.equal(heading(),destination,'completion must not steal navigation');
 run('rf206HealthHub()');held=false;resolveRead=null;pending=run('rf207ReadTodayHealth()');await waitRead();run('rf215WeightScreen()');
 resolveRead({sources:[],source:''});await pending;assert.equal(heading(),weight);
 ctx.bridge={getStatus:async()=>{throw Error('permission denied')}};
 run('rf206HealthHub()');await run('readRecoveryHealth()');
 assert.equal(heading(),hub);assert.equal(run('state.health.busy'),false);
 assert.ok(root.innerHTML.includes('A Health Connect szinkron nem sikerült'),'friendly error visible without navigation');
 assert.ok(run('db.get(RF250_REPORT).errors.join(" ")').includes('permission denied'),'raw diagnostic retained outside normal UI');
 run('healthScreen()');ctx.bridge={requestRead:async()=>({granted:true})};
 await run('healthPermission()');assert.equal(heading(),details);
 console.log('Health routing: background refresh, direct entry, subpages, pending reads, errors and permissions passed');
})().catch(e=>{console.error(e);process.exitCode=1});
