const fs=require('fs'),assert=require('node:assert/strict');
const ui=fs.readFileSync('www/v263.js','utf8');
const index=fs.readFileSync('www/index.html','utf8');
const runtime=fs.readFileSync('www/runtime-manifest.txt','utf8');
assert.match(ui,/RF263_VERSION='2\.6\.3-dev2'/);
assert.match(ui,/RF263_RECOVERY_DAYS=14/);
assert.match(ui,/function rf263NightWindow/);
assert.match(ui,/function rf263RefreshRecovery/);
assert.match(ui,/rf244UnifiedSync=\(\)=>rf263Sync\(\{manual:true\}\)/);
assert.match(ui,/rf241RefreshWorkoutHealth=rf244UnifiedSync/);
assert.match(ui,/Szinkronizálás<\/button>/);
assert.match(ui,/onclick="healthSettings\(\)"[^>]*>Engedélyek<\/button>/);
assert.match(ui,/Kapcsolat és támogatott adatok/);
assert.match(ui,/Engedélyezett adattípusok/);
assert.match(ui,/14 napos éjszakai ellenőrzés/);
assert.match(ui,/sleepStageBased/);
assert.match(ui,/rf260FriendlyHealthSource/);
assert.doesNotMatch(ui,/rf263HealthHub[\s\S]{0,8000}go\('history'\)/);
assert.match(ui,/Coach never performs a Health sync/);
assert.match(ui,/Egészség megnyitása/);
assert.match(ui,/details class="history rf263-history rf103-history"/);
assert.match(ui,/rf103-history-chevron/);
assert.match(ui,/border-radius:16px/);
assert.doesNotMatch(ui,/type="date"/);
assert.match(ui,/rf263DateField/);
assert.match(ui,/Ettől/);
assert.match(ui,/Eddig/);
assert.match(ui,/Szűrés törlése/);
assert.match(index,/v260\.js[\s\S]*v263\.js[\s\S]*ready\.js/);
assert.match(runtime,/^v263\.js$/m);
console.log('PASS 2.6.3-dev2 Health hub + collapsible/filterable history guards.');

